###
POST http://localhost:8080/api/currency
Content-Type: application/json

{
  "name": "dollar"
}

###
PUT http://localhost:8080/api/currency/id=1
Content-Type: application/json

{
  "name": "dollar",
  "active": false
}


###
GET http://localhost:8080/api/currency

###
GET http://localhost:8080/api/currency/id=1

###
DELETE http://localhost:8080/api/currency/id=1
