###
POST http://localhost:8080/api/currency
Content-Type: application/json

{
  "name": "currency 1"
}

###
GET http://localhost:8080/api/currency

###
GET http://localhost:8080/api/currency/id=1

###
DELETE http://localhost:8080/api/currency/id=1
