###
POST http://localhost:8080/api/input
Content-Type: application/json

{
  "warehouseId": 1,
  "supplierId": 2,
  "currencyId": 2,
  "factureNumber": "INV-83478"
}

###
PUT http://localhost:8080/api/input/id=1
Content-Type: application/json

{
  "warehouseId": 1,
  "supplierId": 2,
  "currencyId": 3,
  "factureNumber": "INV-00010"
}

###
GET http://localhost:8080/api/input

###
GET http://localhost:8080/api/input/id=1

###
DELETE http://localhost:8080/api/input/id=1
